alias matlab='/usr/local/MATLAB/R2011b/bin/matlab &'
alias e='emacs &'
alias s='spotify &'
alias p='python3'
alias d='cd $HOME/Desktop'
alias p='cd $HOME/Desktop/private-repo'
alias dl='cd $HOME/Downloads'
alias f='google-chrome &'
alias o='xdg-open .'
alias a='~/bin/android-studio/bin/studio.sh &'
alias b='ssh -L 16115:localhost:16115 cs186-aek@hive23.cs.berkeley.edu'
alias c='ssh -X cs152-an@derby.cs.berkeley.edu'
alias 8='cd $HOME/Desktop/fa15/188'
alias 7='cd $HOME/Desktop/fa15/170'
alias 2='cd $HOME/Desktop/fa15/20'
alias test='python -m doctest -v '
alias question='nano ~/questions'
alias z='synclient TouchpadOff=0'
